// <auto-generated />
using HGN_Task3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HGN_Task3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251103161400_bhjji")]
    partial class bhjji
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HGN_Task3.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<int?>("FlashcardsListModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardsListModelId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("HGN_Task3.Models.FlashcardsListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlashcardsListModels");
                });

            modelBuilder.Entity("HGN_Task3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserFullResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFullResponses");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserItemResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int?>("FlashcardId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnswerKnown")
                        .HasColumnType("boolean");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserFullResponseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("UserFullResponseId");

                    b.ToTable("UserItemResponses");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRequests");
                });

            modelBuilder.Entity("HGN_Task3.Models.Flashcard", b =>
                {
                    b.HasOne("HGN_Task3.Models.FlashcardsListModel", "FlashcardsListModel")
                        .WithMany("Flashcards")
                        .HasForeignKey("FlashcardsListModelId");

                    b.Navigation("FlashcardsListModel");
                });

            modelBuilder.Entity("HGN_Task3.Models.FlashcardsListModel", b =>
                {
                    b.HasOne("HGN_Task3.Models.User", "User")
                        .WithMany("FlashcardsListModels")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserFullResponse", b =>
                {
                    b.HasOne("HGN_Task3.Models.User", "User")
                        .WithMany("UserFullResponses")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserItemResponse", b =>
                {
                    b.HasOne("HGN_Task3.Models.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId");

                    b.HasOne("HGN_Task3.Models.UserFullResponse", null)
                        .WithMany("UserItemResponses")
                        .HasForeignKey("UserFullResponseId");

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserRequest", b =>
                {
                    b.HasOne("HGN_Task3.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HGN_Task3.Models.FlashcardsListModel", b =>
                {
                    b.Navigation("Flashcards");
                });

            modelBuilder.Entity("HGN_Task3.Models.User", b =>
                {
                    b.Navigation("FlashcardsListModels");

                    b.Navigation("UserFullResponses");
                });

            modelBuilder.Entity("HGN_Task3.Models.UserFullResponse", b =>
                {
                    b.Navigation("UserItemResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
